Add missing permissions for peter-evans/create-pull-request@v5 (#375)
Follow-up to #374

This commit fixes the error with the "Update Awesome Stylelint" workflow. See the log:

```
/usr/bin/git push --force-with-lease origin create-pull-request/patch:refs/heads/create-pull-request/patch
remote: Permission to stylelint/stylelint.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/stylelint/stylelint.io/': The requested URL returned error: 403
Error: The process '/usr/bin/git' failed with exit code 128
```

-- https://github.com/stylelint/stylelint.io/actions/runs/7369219181/job/20054275649#step:6:89

See also https://github.com/peter-evans/create-pull-request/issues/1873